services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express-ui
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo
    networks:
      - app-network

  redis:
    image: redis:latest
    restart: always
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx-proxy
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - node-app-dev
      - node-app-prod
    networks:
      - app-network

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres-db
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  node-app-dev:
    build:
      context: .
      target: development
    container_name: node-app-dev
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
    ports:
      - "4001:4000"
    depends_on:
      - mongo
      - mongo-express
      - redis
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

  node-app-prod:
    build:
      context: .
      target: production
    container_name: node-app-prod
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    ports:
      - "4002:4000"
    depends_on:
      - mongo
      - redis
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local
  postgres_data:
    driver: local
